const SET_PLAYER_PLAYING = 'SET_PLAYER_PLAYING';
const SET_PLAYER_PROGRESS = 'SET_PLAYER_PROGRESS';
const SET_PLAYER_DURATION = 'SET_PLAYER_DURATION';
const SET_LOADING = 'SETLOADING';

const SET_REDIO_SHOW_STATE = 'SET_TO_PLAYER_STREAM_AUDIO';

const SET_PLAYER_PROGRESS_BAR_HOLDING = 'SET_PLAYER_PROGRESS_BAR_HOLDING';
const SET_PLAYER_ACTIVE_PROGRESS_BAR = 'SET_PLAYER_ACTIVE_PROGRESS_BAR';

const SET_PLAYER_VOLUME = 'SET_PLAYER_VOLUME';
const SET_PLAYER_MUTE_VOLUME = 'SET_PLAYER_MUTE_VOLUME';

const SET_PLAYER_POSTION_TOOLTIP_BAR = 'SET_POSTION_TOOLTIP_BAR';

const SET_SHOW_NAME_BY_AUTHOR = 'SET_SHOW_NAME_BY_AUTHOR';

const SET_PLAYER_QUEUE_SHOW = 'SET_PLAYER_QUEUE_SHOW';
const SET_VISIBILITY_QUEUE_PANEL = 'SET_VISIBILITY_QUEUE_PANEL';
const SET_REMOVE_FROM_QUEUE = 'SET_REMOVE_FROM_QUEUE';

const SET_TOGGLE_POPPER = 'SET_TOGGLE_POPPER';
const SET_SETTING_MODE = 'SET_SETTING_MODE';

export {
  SET_PLAYER_PLAYING,
  SET_PLAYER_PROGRESS,
  SET_PLAYER_DURATION,
  SET_REDIO_SHOW_STATE,
  SET_PLAYER_PROGRESS_BAR_HOLDING,
  SET_PLAYER_ACTIVE_PROGRESS_BAR,
  SET_PLAYER_VOLUME,
  SET_PLAYER_MUTE_VOLUME,
  SET_PLAYER_POSTION_TOOLTIP_BAR,
  SET_SHOW_NAME_BY_AUTHOR,
  SET_PLAYER_QUEUE_SHOW,
  SET_VISIBILITY_QUEUE_PANEL,
  SET_REMOVE_FROM_QUEUE,
  SET_TOGGLE_POPPER,
  SET_SETTING_MODE,
  SET_LOADING
};